TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 0.9
  min_vel_theta: -0.9
  min_in_place_vel_theta: 0.2

  acc_lim_theta: 0.7
  acc_lim_x: 0.1
  acc_lim_y: 0.1

  holonomic_robot: true
  meter_scoring: true
  use_dwa: true
  xy_goal_tolerance: 0.2 
  yaw_goal_tolerance: 3.14


EBandPlannerROS:
 # Common Parameters
 xy_goal_tolerance: 0.05
 yaw_goal_tolerance: 3.14
 rot_stopped_vel: 0.01
 trans_stopped_vel: 0.01


 # Elastic Band Parameters
 eband_min_relative_overlap: 0.7
 eband_tiny_bubble_distance: 0.01
 eband_tiny_bubble_expansion: 0.01
 eband_internal_force_gain: 1.0
 eband_external_force_gain: 2.0
 num_iterations_eband_optimization: 3
 eband_equilibrium_approx_max_recursion_depth: 4
 eband_equilibrium_relative_overshoot: 0.75
 eband_significant_force_lower_bound: 0.15
 costmap_weight: 10.0
 
 # Trajectory Controller Parameters
 max_vel_lin: 2.0
 min_vel_lin: 0.1
 max_vel_th: 0.0
 min_vel_th: 0.0
 min_in_place_vel_th: 0.0
 in_place_trans_vel: 0.0
 k_prop: 4.0
 k_damp: 3.5
 max_acceleration: 0.8
 max_translational_acceleration: 1.0
 max_rotational_acceleration: 1.5
 rotation_correction_threshold: 0.5
 differential_drive: false
 bubble_velocity_multiplier: 2.0
 rotation_threshold_multiplier: 1.0
 disallow_hysteresis: false




DWAPlannerROS:
  holonomic_robot: true
  acc_lim_th: 0.0 
  acc_lim_x: 1.0 
  acc_lim_y: 1.0 


  max_vel_x: 0.4 
  min_vel_x: -10

  max_vel_y: 0.4 
  min_vel_y: -10 

  max_trans_vel: 0.65 
  min_trans_vel: -10 
  max_rot_vel: 1.0 
  min_rot_vel: -1.0 

  sim_time: 3.5 
  sim_granularity: 0.025 
  occdist_scale: 0.01 
  stop_time_buffer: 0.2 
  oscillation_reset_dist: 0.05 
  forward_point_distance: 0.325 
  scaling_speed: 0.25 
  max_scaling_factor: 0.2 
  vx_samples: 10 
  vy_samples: 10 
  vtheta_samples: 20 
  xy_goal_tolerance: 0.2 
  yaw_goal_tolerance: 3.14
  rot_stopped_vel: 0.01 
  trans_stopped_vel: 0.01
