TrajectoryPlannerROS:
   max_vel_x: 0.2
   min_vel_x: 0.1
   max_vel_y: 0.2  # zero for a differential drive robot
   min_vel_y: 0.1
   max_vel_theta: 1.0
   min_vel_theta: -1.0
   min_in_place_vel_theta: 0.4
   escape_vel: -0.1
   acc_lim_x: 1.0
   acc_lim_y: 1.0  # zero for a differential drive robot
   acc_lim_theta: 1.0

   holonomic_robot: true

   vx_samples: 8
   vy_samples: 8 

