obstacle_range: 5.0
raytrace_range: 5.0
footprint: [[1.2, 1.2], [-1.2, 1.2], [-1.2, -1.2], [1.2, -1.2]]
inflation_radius: 5.0

max_obstacle_height: 3.0
min_obstacle_height: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}


