obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.5, 0.5], [-0.5, 0.5], [-0.5, -0.5], [0.5, -0.5]]
inflation_radius: 0.5
robot_radius: 0.4

max_obstacle_height: 3.0
min_obstacle_height: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: uav_laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}


