global_costmap:
  global_frame: uav_odom
  robot_base_frame: uav_base_stabilized
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 50.0
  height: 50.0
  resolution: 0.1

