local_costmap:
  global_frame: uav_odom
  robot_base_frame: uav_base_stabilized
  update_frequency: 20.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.05

